# Generated by Django 4.1 on 2023-07-17 00:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("usuarios", "0002_configuracionpaginas_estado_paginas_empresas"),
    ]

    operations = [
        migrations.AlterField(
            model_name="proyecto",
            name="modalidad",
            field=models.CharField(
                choices=[
                    ("", "Selecciona una opción"),
                    ("Presencial", "Presencial"),
                    ("Remoto", "Remoto"),
                    ("Mixta", "Mixta"),
                ],
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="proyecto",
            name="periodo",
            field=models.CharField(
                choices=[
                    ("", "Selecciona una opción"),
                    ("Enero-Abril", "Enero-Abril"),
                    ("Mayo-Agosto", "Mayo-Agosto"),
                    ("Septiembre-Diciembre", "Septiembre-Diciembre"),
                ],
                max_length=25,
            ),
        ),
    ]
